import os
import subprocess
import shutil
import sys
import stat
from pathlib import Path

# Configurações Antigravity v6.0
ROOT_DIR = Path(".")
AGENTS_DIR = ROOT_DIR / ".agent"
TEMP_DIR = ROOT_DIR / "temp_skill_import"

def remove_readonly(func, path, excinfo):
    """Manipulador para remover arquivos somente-leitura (comum em Windows/.git)."""
    os.chmod(path, stat.S_IWRITE)
    func(path)

def run_command(command, cwd=None):
    """Executa comando shell e retorna saída."""
    result = subprocess.run(command, shell=True, capture_output=True, text=True, cwd=cwd)
    return result.stdout, result.stderr

def generate_skill_from_repo(repo_url, category="uncategorized"):
    """Clona um repo, analisa e gera uma Skill Antigravity."""
    repo_name = repo_url.split("/")[-1].replace(".git", "")
    target_dir = AGENTS_DIR / category / repo_name
    
    print(f"[*] Instando Skill v6.0: {repo_name}...")
    
    if target_dir.exists():
        print(f"[!] Erro: Skill '{repo_name}' já existe em {target_dir}")
        return False

    try:
        # 1. Clone temporário
        if TEMP_DIR.exists(): shutil.rmtree(TEMP_DIR, onerror=remove_readonly)
        print(f"[*] Clonando {repo_url}...")
        stdout, stderr = run_command(f"git clone --depth 1 {repo_url} {TEMP_DIR}")
        
        if not TEMP_DIR.exists():
            print(f"[!] Erro ao clonar: {stderr}")
            return False

        # 2. Análise de Conteúdo (Simulada para v6.0 - Otimizada por LLM no Router)
        # Em um fluxo real, o orquestrador leria estes arquivos para gerar o SKILL.md
        readme_path = TEMP_DIR / "README.md"
        readme_content = readme_path.read_text(errors="ignore")[:3000] if readme_path.exists() else "No README found."
        
        # 3. Criar estrutura de Skill
        target_dir.mkdir(parents=True, exist_ok=True)
        
        # Gerar o arquivo SKILL.md
        skill_content = f"""# 🛠️ Skill: {repo_name}
Categoria: {category}
Origem: {repo_url}

## 🚀 Sobre
{readme_content[:1000]}...

## 📂 Estrutura de Arquivos Importantes
{", ".join([f.name for f in list(TEMP_DIR.iterdir())[:10]])}

## 🎯 Quando Usar
- Ao trabalhar com funcionalidades específicas de {repo_name}
- Para integrar este repositório como ferramenta no workflow Antigravity

## 💡 Prompt de Ativação
"Utilize o conhecimento da skill {repo_name} para [tarefa]"

---
[Auto-Generated by Antigravity v6.0 Universal Generator]
"""
        (target_dir / "SKILL.md").write_text(skill_content, encoding="utf-8")
        
        # 4. Limpeza e Indexação
        shutil.rmtree(TEMP_DIR, onerror=remove_readonly)
        print(f"[OK] Skill '{repo_name}' gerada com sucesso!")
        
        # Trigger indexer
        from index_skills import index_all
        index_all()
        
        return True

    except Exception as e:
        print(f"[!] Erro durante a geração: {e}")
        if TEMP_DIR.exists(): shutil.rmtree(TEMP_DIR, onerror=remove_readonly)
        return False

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Uso: python skill_generator.py [URL_REPO] [CATEGORIA(opcional)]")
        sys.exit(1)
        
    url = sys.argv[1]
    cat = sys.argv[2] if len(sys.argv) > 2 else "uncategorized"
    generate_skill_from_repo(url, cat)
